"""Rename shelf

Revision ID: 6953188fe48d
Revises: bb219cef3a68
Create Date: 2023-10-16 23:01:20.025443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6953188fe48d'
down_revision: Union[str, None] = 'bb219cef3a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelves', sa.Column('shelf_name', sa.String(), nullable=False))
    op.drop_column('shelves', 'shelf_main')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelves', sa.Column('shelf_main', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('shelves', 'shelf_name')
    # ### end Alembic commands ###
