"""Initial

Revision ID: bb219cef3a68
Revises: 
Create Date: 2023-10-16 22:46:03.391144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb219cef3a68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_shelf_association', sa.Column('is_main', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'product_shelf_association', 'shelves', ['shelf_id'], ['id'])
    op.add_column('shelves', sa.Column('shelf_main', sa.String(), nullable=False))
    op.drop_column('shelves', 'shelf_main_name')
    op.drop_column('shelves', 'shelf_additional_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelves', sa.Column('shelf_additional_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shelves', sa.Column('shelf_main_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('shelves', 'shelf_main')
    op.drop_constraint(None, 'product_shelf_association', type_='foreignkey')
    op.drop_column('product_shelf_association', 'is_main')
    # ### end Alembic commands ###
